### ISSUE TITLE
Feedback on v3.9.0

### ISSUE THREAD

**Issue by rcoletti116** [colinbendell/homebridge-blink-for-home#100]
Hi Colin - thanks for a big update to the plugin. I really appreciate the work you put in here. This one has some significant changes and I wanted to provide some general feedback from testing so far.

- 2 Factor Auth is working well.

- Experimental Live-View: I suspect this is because my camera (XT2) is not supported, but the effect may not be expected. When this is turned on it causes homebridge to crash for me. I can raise a separate issue for this if this is not a known behavior.

- Thumbnail refresh - I know there's been some debate over when or how frequently thumbnails should be updated. Some folks don't want it to ever update or are concerned about battery. I like the regular updates, as my camera doesn't support streaming the refreshed thumbnails give me a sense of what is going on. So I don't love the requirement to have both motion enabled and the camera armed for thumb refreshes. Otherwise the new functionality seems to be working as expected.

- Features Settings UI says "By default, the camera view will expose the last recorded motion." Does this mean actual video recordings or just thumbnails? I know you wrote the CLI that could pull recordings a while back. Just curious on how this should function.

Thanks again!

**Comment by colinbendell** [comment]
Thanks!

* I haven't yet returned to work on the liveview. It's on the TODO list
* To make sure I understand your desire. You have, for example, a camera pointing in your backyard. You are home, so you don't want the motion alerts. But you want the periodic updated thumbnail when looking at it through the home app. Is that about right? (fwiw, I removed this specific part of the code because it was messy and hard to test the logic. I've done a bunch of refactoring, so it's not as bad and can probably add it back)
* I don't yet know how to send an 'old motion' to HKSC. I don't even know if that is possible in HK in general. The intention is that the last motion thumbnail can be used.

**Comment by rcoletti116** [comment]
> * To make sure I understand your desire. You have, for example, a camera pointing in your backyard. You are home, so you don't want the motion alerts. But you want the periodic updated thumbnail when looking at it through the home app. Is that about right? (fwiw, I removed this specific part of the code because it was messy and hard to test the logic. I've done a bunch of refactoring, so it's not as bad and can probably add it back)

Pretty much! I also use the HomeCam app as kind of a dashboard and it pull thumbnails and shows multiple cams.

**Comment by town3r** [comment]
Happy to see this plugin is still being worked on!

Since updating my camera is stuck on Off.

Manually Disabled seems to be auto enabled.

Current settings:

```
 "hide-alarm": true,
            "hide-manual-arm-switch": true,
            "hide-enabled-switch": true,
            "hide-privacy-switch": true,
            "enable-liveview": true,
            "disable-thumbnail-refresh": false,
            "enable-startup-diagnostic": false,
            "platform": "Blink"
```

**Comment by town3r** [comment]
Ope, looks like it's causing homebridge to crash.

![image](https://user-images.githubusercontent.com/12396203/160698839-f294b1ac-bdd4-49a6-8e53-ebb6077ddab3.jpeg)

**Comment by town3r** [comment]
Apologies for all the responses.

I found that disabling the LiveView feature (which was working before) seems to resolve the issue with the thumbnail not loading and homebridge crashing

**Comment by colinbendell** [comment]
the live view should only be triggering if you tap into the camera. Homekit does get into a little bit of a state when it gets an error for loading the live view and takes a bit to refresh out of it.

**Comment by pserbanp** [comment]
> 

Same for me all cameras are OFF.  Thank you for continue developing

**Comment by rcoletti116** [comment]
Arm the cameras to get them back "on".

**Comment by gdotp01** [comment]
Good to see this is still being worked on. Thanks for your efforts.

I’ve updated and all cameras (all 6) seem to be off and don’t change from this even if the system is armed.

![670E361C-D661-4D4C-B289-079E56C31F52](https://user-images.githubusercontent.com/50060482/160915968-dcae6f2b-14a2-40a9-96f6-fdb0a5fa9a79.png)

**Comment by pserbanp** [comment]
> Good to see this is still being worked on. Thanks for your efforts.
> 
> I’ve updated and all cameras (all 6) seem to be off and don’t change from this even if the system is armed.
> 
> ![670E361C-D661-4D4C-B289-079E56C31F52](https://user-images.githubusercontent.com/50060482/160915968-dcae6f2b-14a2-40a9-96f6-fdb0a5fa9a79.png)

Did any of you manage to enable cameras with 3.9.0 ? If I downgrade they are enabled and working ! Simply does not meter if is armed or not there is now streaming working

**Comment by gdotp01** [comment]
I can’t get it to work at all I’m afraid. It does allow me to turn them on/off but getting no thumbnails. I’ve set up each camera to “streaming” within HomeKit.

**Comment by gdotp01** [comment]
I’ve returned to the previous version and it’s working as expected again

**Comment by colinbendell** [comment]
Change the camera to 'detect activity' to avoid the camera from attempting to stream. Streaming is broken in general (see comments in other threads about the proprietary steraming format), and a bit more broken in this release. 

The thumbnails should then show up after disabling the camera and re-enabling it.

**Comment by gdotp01** [comment]
I’ve updated and set to Detect activity rather than streaming. However still no thumbnails. I’ll cameras are blank and say “detect activity”. I’m not sure what you mean when you say disable the cameras , where would I do this ? 

![EE2C1520-F0F2-43A8-B148-EC33674AE1F8](https://user-images.githubusercontent.com/50060482/161647582-98447b65-b5a3-4154-b8c4-3ebfb91ff15d.png)

**Comment by colinbendell** [comment]
Ah sorry, I didn't realize homekit turns off the thumbnails when you do that. The best way I have found to reset homekit's polling of the thumbnails is to either 'disarm then arm' the cameras using the switches, or temporarily disable the plugin (restart homebridge, re-enbable the plugin). There are many reddit threads discussing this.

The alternative is that I set up a passive RSTP stream so that live view appears to be working, even though it is not.

**Comment by StaRipper** [comment]
Same here.

**Comment by gdotp01** [comment]
I’ve tried every way I can think of to get this to work but eventually I’ve gone back to the previous version I’m afraid

**Comment by 1PlusN** [comment]
I'm having a pain of a time with 3.9.0 as well. The Camera shows as disables or off *sometimes* and other times I get a thumbnail refresh (not per the refresh rate setting though). I just enables the logging, and the getSirens() seems to be throwing an error. 
`[11/04/2022, 21:29:33] [Blink] GET /sirens (404 Not Found)
[11/04/2022, 21:29:33] [Blink] GET /sirens
[11/04/2022, 21:29:33] [Blink] Error: GET /sirens (404 Not Found)
    at BlinkAPI._request (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:342:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BlinkAPI.get (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:228:16)
    at BlinkAPI.getSirens (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:1114:16)
    at anonymize (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:469:25)
    at BlinkHAP.diagnosticDebug (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:507:13)
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[11/04/2022, 21:29:33] [Blink] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at anonymize (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:472:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BlinkHAP.diagnosticDebug (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:507:13)
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[11/04/2022, 21:29:33] [Blink] Error: Blink Authentication failed.
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:116:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[11/04/2022, 21:29:33] [Blink] NOTE: Blink devices in HomeKit will not be responsive.`
