### ISSUE TITLE
Error: Audio was enabled but not supplied in PrepareStreamResponse!

### ISSUE THREAD

**Issue by rbenjamint** [colinbendell/homebridge-blink-for-home#102]
I updated to latest version, when viewing the camera, I get this error and after this error its restarting whole homebridge.

`Error: Audio was enabled but not supplied in PrepareStreamResponse!
    at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1124:13)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1094:16
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at BlinkCameraDelegate.prepareStream (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/blink-camera-deligate.js:132:9)`

Anyone else with this issue? And what to do about it?

**Comment by colinbendell** [comment]
update to 3.9.1 should fix this.
