### ISSUE TITLE
2FA again -- is it solved?

### ISSUE THREAD

**Issue by Kalie15** [colinbendell/homebridge-blink-for-home#114]
Hi there! Is the 2FA problem solved? I get a 2FA token via SMS, but no email and no other way that Homebridge can now be added to the list of trusted devices. As a result, I can't access the cameras, the error message is always that authentication fails. Is there a solution for this?

**Comment by Kalie15** [comment]
[6/6/2022, 8:53:49 AM] [Blink] GET &#x2F;sirens
[6/6/2022, 8:53:49 AM] [Blink] GET /sirens (404 Not Found)
[6/6/2022, 8:53:49 AM] [Blink] GET &#x2F;sirens
[6/6/2022, 8:53:49 AM] [Blink] Error: GET /sirens (404 Not Found)
    at BlinkAPI._request (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:342:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BlinkAPI.get (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:228:16)
    at BlinkAPI.getSirens (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:1114:16)
    at anonymize (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:469:25)
    at BlinkHAP.diagnosticDebug (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:507:13)
    at HomebridgeBlink.setupBlink (/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[6/6/2022, 8:53:49 AM] [Blink] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at anonymize (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:472:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BlinkHAP.diagnosticDebug (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:507:13)
    at HomebridgeBlink.setupBlink (/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[6/6/2022, 8:53:49 AM] [Blink] Error: Blink Authentication failed.
    at HomebridgeBlink.setupBlink (/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:116:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HomebridgeBlink.init (/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[6/6/2022, 8:53:49 AM] [Blink] NOTE: Blink devices in HomeKit will not be responsive.

**Comment by abrahamneben** [comment]
Same issue here.

**Comment by Kalie15** [comment]
Hello,

Thank you for contacting Blink Technical Support.
We really apologized for the inconvenience that it cause to you.

We regret to inform you that Blink does not support HomeBridge. At this time, we only allow IFTTT and Amazon Alexa enabled devices to integrate with Blink for additional features and linking to other hardware.

If you have further inquiry please do not hesitate to contact us. Thank you!
​


Best Regards,

"Mic" Mico,
Blink Technical Support

Blink Phone line: +1 781-332-5465
My Office Hours: 9 AM - 6 PM EST, Mon-Fri

**Comment by MetahumanFamily** [comment]
Same issue.

Due to Blink service-side update?

Thanks,

**Comment by shaktimaan** [comment]
Same response here: GET /sirens (404 Not Found) :(

**Comment by MetahumanFamily** [comment]
UPDATE: After changing password, I was able to get logged in with the plugin using 2FA code and all devices working as expected.

**Comment by abrahamw88** [comment]
Same issue here… any ideas? I tried changing my password and that didn’t work.
