### ISSUE TITLE
TX Ultimate 1 Gang

### ISSUE THREAD

**Issue by lcmds** [colinbendell/homebridge-blink-for-home#144]
I'm getting this error when I try to turn my lights on using Homebridge UI through the Accessories TAB. [Office Lights ] device update failed as unknown WS response [400] at default.sendUpdate (file:///var/lib/homebridge/node_modules/homebridge-ewelink/lib/connection/ws.js:339:19) at default.sendUpdate (file:///var/lib/homebridge/node_modules/homebridge-ewelink/lib/connection/ws.js:344:15). Device Model T5-1C-86 (SN-ESP32D0-T5-01). Let me know if you need further information.

**Comment by lcmds** [comment]
.
