### ISSUE TITLE
Camera offline

### ISSUE THREAD

**Issue by carlo0806** [colinbendell/homebridge-blink-for-home#145]
Thumbnail are working fine, but if i click for live view it shows "camera offline"
Is there a quick fix?

**Comment by KasimF** [comment]
Having the same issue with Blink outdoor cameras

**Comment by bluntiless** [comment]
Same here, I have had this problem for some time now but, none of the fixes have worked for me. Debug logs do not appear to show any errors, so very difficult to pin down what the issue might be. The last time I had this working was on an older version, 3.7 and Homebridge was on older version as well.

**Comment by DrallocBen** [comment]
Hi ! 

Same issue here, I was able to collect an error when bridging the plugin. 

```
homebridge/node_modules/homebridge-blink-for-home/src/blink.js:307
        const data = await this.blink.getUrl(thumbnailUrl.replace(/\.jpg|$/, '.jpg'));
                                                          ^
TypeError: Cannot read properties of null (reading 'replace')
    at BlinkCameraHAP.getThumbnail (/volume1/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:307:59)
    at BlinkCameraDelegate.handleSnapshotRequest (/volume1/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/blink-camera-deligate.js:77:47)
    at /volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:1030:23
    at new Promise (<anonymous>)
    at CameraController.handleSnapshotRequest (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:1009:12)
    at Bridge.Accessory.handleResource (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1936:18)
    at HAPServer.emit (node:events:513:28)
    at HAPServer.handleResource (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:1054:12)
    at IncomingMessage.<anonymous> (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:430:11)
    at IncomingMessage.emit (node:events:513:28)
```

**Comment by codingwithmac** [comment]
Hello! I am having this issue as well.
Has anyone found a fix for this issue?
