### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by mfduarte** [colinbendell/homebridge-blink-for-home#150]
Hello - after getting the 2FA code via email, entering the code in the plugin settings, and restarting HomeBridge, I see the following errors in the log:

[10/18/2023, 9:52:27 AM] [Blink] getBlinkStatus()
[10/18/2023, 9:52:27 AM] [Blink] SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at CacheableResponse.json (/usr/local/lib/node_modules/homebridge-blink-for-home/node_modules/@adobe/fetch/src/fetch/cacheableResponse.js:93:17)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at BlinkAPI._request (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:290:26)
at BlinkAPI.get (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:229:16)
at BlinkAPI.getBlinkStatus (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:1282:16)
at anonymize (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:469:25)
at BlinkHAP.diagnosticDebug (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:499:13)
at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[10/18/2023, 9:52:27 AM] [Blink] TypeError: Cannot read properties of undefined (reading 'replaceAll')
at anonymize (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:472:33)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at BlinkHAP.diagnosticDebug (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:499:13)
at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[10/18/2023, 9:52:27 AM] [Blink] Error: Blink Authentication failed.
at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:116:19)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[10/18/2023, 9:52:27 AM] [Blink] NOTE: Blink devices in HomeKit will not be responsive.

**Comment by taraye308** [comment]
Receiving the same error. Receiving a similar error. Running node version  v20.10.0 and HomeKit v1.7.0 and UI v4.55.1


`[14/01/2024, 12:34:11] [Blink] ====== START BLINK DEBUG ======
[14/01/2024, 12:34:11] [Blink] POST /api/v5/account/login @null
[14/01/2024, 12:34:11] [Blink] GET /user @1
[14/01/2024, 12:34:11] [Blink] GET /api/v3/accounts/88031/homescreen @0
[14/01/2024, 12:34:11] [Blink] SyntaxError: Invalid regular expression: /\b******7390\b/g: Nothing to repeat
    at new RegExp (<anonymous>)
    at BlinkHAP.diagnosticDebug (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:465:37)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HomebridgeBlink.setupBlink (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[14/01/2024, 12:34:11] [Blink] Error: Blink Authentication failed.
    at HomebridgeBlink.setupBlink (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:116:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HomebridgeBlink.init (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[14/01/2024, 12:34:11] [Blink] NOTE: Blink devices in HomeKit will not be responsive. `
