### ISSUE TITLE
refreshThumbnail undefined - v3.5.15 

### ISSUE THREAD

**Issue by rcoletti116** [colinbendell/homebridge-blink-for-home#17]
Started getting this after updating to 3.5.15. 

(node:21522) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'refreshThumbnail' of undefined
    at BlinkCameraDelegate.handleSnapshotRequest (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-camera-deligate.js:123:30)
    at CameraController.handleSnapshotRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:351:23)
    at Bridge.Accessory._handleResource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1531:18)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleResource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:918:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:21522) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21522) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by colinbendell** [comment]
My bad. can you try the 3.5.16?

**Comment by rcoletti116** [comment]
Yes, this error is resolved. 

I'll open a new issue related to liveview on XT2. Attempting to do liveview crashes homebridge.
