### ISSUE TITLE
LiveView Crashes Homebridge

### ISSUE THREAD

**Issue by rcoletti116** [colinbendell/homebridge-blink-for-home#18]
Plugin v3.5.16
Camera XT2

Issue: Liveview crashes homebridge.

Logs:
LiveView Stream: immis://3.90.188.64:443/ZUvX-uuGH7thyqTf__IMDS_890261671?client_id=46
listening on 0.0.0.0:34167
client connected from 127.0.0.1:48316
[11/10/2020, 09:40:31] TypeError: console.tls is not a function
    at Server.connectionListener (/usr/local/lib/node_modules/homebridge-blink-for-home/src/proxy.js:27:21)
    at Server.emit (events.js:315:20)
    at TCP.onconnection (net.js:1555:8)
[11/10/2020, 09:40:31] Got SIGTERM, shutting down Homebridge...

**Comment by colinbendell** [comment]
another embarrassing typo. fixed.
