### ISSUE TITLE
Unable to Arm any systems

### ISSUE THREAD

**Issue by kevanwm** [colinbendell/homebridge-blink-for-home#33]
Hi Colin - First up... Fantastic work. Your plugin has been a great help since IFTT and Life360 stopped supporting location triggers.

Unfortunately, something major has gone wrong with my setup.

I've got 4 separate blink systems running in the Homebridge with the homebridge-blink-for-home plugin.

All was working until recently, I realised systems were not arming when leaving the house.

It seems I'm getting this error in Homebridge - that's causing arm to fail.

```
[12/8/2020, 7:40:56 PM] [blink-mccolgan] Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM
    at ClientHttp2Stream._destroy (internal/http2/core.js:2115:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2131:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:513:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
[12/8/2020, 7:40:56 PM] [blink-mccolgan] Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM
    at ClientHttp2Stream._destroy (internal/http2/core.js:2115:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2131:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:513:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
[12/8/2020, 7:41:01 PM] [blink-mccolgan] Error: getaddrinfo ENOTFOUND rest-prde.immedia-semi.comundefined.jpg
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'rest-prde.immedia-semi.comundefined.jpg'
}
(node:2846) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND rest-prde.immedia-semi.comundefined.jpg
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
(node:2846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:2846) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12/8/2020, 7:43:07 PM] [blink-mccolgan] Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM
    at ClientHttp2Stream._destroy (internal/http2/core.js:2115:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2131:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:513:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
[12/8/2020, 7:43:07 PM] [blink-mccolgan] Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM
    at ClientHttp2Stream._destroy (internal/http2/core.js:2115:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2131:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:513:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
[12/8/2020, 7:43:19 PM] [blink-mccolgan] Error: getaddrinfo ENOTFOUND rest-prde.immedia-semi.comundefined.jpg
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'rest-prde.immedia-semi.comundefined.jpg'
}
(node:2846) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND rest-prde.immedia-semi.comundefined.jpg
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
(node:2846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
```

Versions are:
Raspbian GNU/Linux Buster (10)
Homebridge: 1.2.4 (although the issue was originally happening on 1.2.3 - I've since updated to see if that cured it)
homebridge-config-ui-x v4.36.0
homebridge-blink-for-home v3.6.2

**Comment by rcoletti116** [comment]
Oh, I just opened another case - #34 - with these same errors. I didn't realize this impacted arming, but I just tested and it does appear arming doesn't work. I assumed something is wrong with the live view function since  a) I have liveview disabled in the plugin and b) no one is trying to view these cams when the errors occur.

FWIW I also did find out that this plugin does not work on the Homebridge 1.3 Beta. I'm running 1.2.4 as well.

**Comment by colinbendell** [comment]
sorry for long comms silence. can you verify that in v3.7 that these issues have been addressed?

**Comment by kevanwm** [comment]
@colinbendell - tried v3.7.1 and am hitting this issue: https://github.com/colinbendell/homebridge-blink-for-home/issues/56#issuecomment-783626996
