### ISSUE TITLE
Stream Errors When Not Streaming

### ISSUE THREAD

**Issue by rcoletti116** [colinbendell/homebridge-blink-for-home#34]
Since streaming doesn't work my cameras I have LiveView disabled in the plugin. Still, I get the below errors, and no one is attempting to stream. They just appear in the logs.

`[12/10/2020,` 08:59:17] [Blink] Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM
    at ClientHttp2Stream._destroy (internal/http2/core.js:2110:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2126:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:511:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
[12/10/2020, 08:59:18] [Blink] Error: getaddrinfo ENOTFOUND rest-u008.immedia-semi.comundefined.jpg
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'rest-u008.immedia-semi.comundefined.jpg'
}
(node:710) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND rest-u008.immedia-semi.comundefined.jpg
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
(node:710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2821)`

**Comment by rcoletti116** [comment]
Seems this is a Duplicate of #33
