### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by donavanbecker** [colinbendell/homebridge-blink-for-home#40]
```[1/4/2021, 8:46:15 AM] [Blink] TypeError: this.enqueueConfigurationUpdate is not a function
    at PlatformAccessory.Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:444:12)
    at BlinkNetwork.createAccessory (/usr/lib/node_modules/homebridge-blink-for-home/src/blink.js:195:37)
    at /usr/lib/node_modules/homebridge-blink-for-home/src/index.js:54:60
    at Array.map (<anonymous>)
    at HomebridgeBlink.init (/usr/lib/node_modules/homebridge-blink-for-home/src/index.js:54:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[1/4/2021, 8:46:15 AM] [Blink] NOTE: Blink devices in HomeKit will not be responsive.```

**Comment by colinbendell** [comment]
can you verify with v3.7?

**Comment by donavanbecker** [comment]
I haven't seen it since v3.7, Thanks!
