### ISSUE TITLE
TypeError: Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by donavanbecker** [colinbendell/homebridge-blink-for-home#52]
Log:
```
[2/20/2021, 8:44:34 PM] [Blink] TypeError: Cannot read property 'context' of undefined
    at BlinkNetwork.get armedAt [as armedAt] (/usr/lib/node_modules/homebridge-blink-for-home/src/blink.js:182:31)
    at BlinkCamera.getMotionDetected (/usr/lib/node_modules/homebridge-blink-for-home/src/blink.js:388:39)
    at MotionDetected.getCallback (/usr/lib/node_modules/homebridge-blink-for-home/src/blink.js:91:53)
    at MotionDetected.emit (events.js:315:20)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1466:14
    at new Promise (<anonymous>)
    at MotionDetected.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1464:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
```
Config:
```
{
    "name": "Blink",
    "username": "email",
    "password": "password",
    "pin": pin,
    "hide-alarm": true,
    "hide-manual-arm-switch": true,
    "hide-enabled-switch": true,
    "hide-privacy-switch": true,
    "enable-liveview": true,
    "avoid-thumbnail-battery-drain": true,
    "enable-verbose-logging": false,
    "enable-debug-logging": false,
    "enable-startup-diagnostic": false,
    "platform": "Blink"
}
```

**Comment by donavanbecker** [comment]
@colinbendell When you set this to true is when you get this error.

```
"hide-manual-arm-switch": true,
```

**Comment by colinbendell** [comment]
ah. you are hiding both the manual-arm-switch and the alarm? I wondered if this would cause an issue when I added [the null check](https://github.com/colinbendell/homebridge-blink-for-home/blob/19b150970342da6e8b39c5548ba71382e69c8366/src/blink.js#L277). My suggestion for now is to enable one of the two accessories for the network (either alarm, or the manual arm switch). The issue is that Blink has this architecture of a 'network' which contain 'cameras' and so you arm the 'network' but not cameras. Since the homebridge design is currently a pass through for Blink's architecture we need to expose at least one accessory.

**Comment by donavanbecker** [comment]
@colinbendell yeah for now I am am just exposing one.
