### ISSUE TITLE
I got this error when i installed the new version:

### ISSUE THREAD

**Issue by MasterofKungfu9999** [colinbendell/homebridge-blink-for-home#53]
43 Error loading platform requested in your config.json at position 7
21.2.2021, 20:10:43 Error: The requested platform 'Blink' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:334:45
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:320:31)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by colinbendell** [comment]
There is likely another error in the logs that causes the Blink plugin to fail to load. Can you restart the server and provide that stack trace?

**Comment by MasterofKungfu9999** [comment]
Sorry, i deinstalled the Plugin

**Comment by MasterofKungfu9999** [comment]
I think i got. the Problem:

21.2.2021, 22:23:20 [2/21/2021, 22:23:20] The plugin "homebridge-blink-for-home" requires a Homebridge version of >=1.2.0 which does not satisfy the current Homebridge version of 1.1.7. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.
21.2.2021, 22:23:20 Error loading plugin "homebridge-blink-for-home"
21.2.2021, 22:23:20 /home/hoobs/.hoobs/node_modules/homebridge-blink-for-home/src/inifile.js:10
            const [name, ...value] = line?.trim()?.split(/=/);
                                          ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-blink-for-home/src/blink-api.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-blink-for-home/src/blink.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)

**Comment by colinbendell** [comment]
Yep. That's it the error: You need homebridge 1.2 or 1.3 (latest) to use the plugin. You are running homebridge 1.1.7 (2 major releases behind). Try upgrading homebridge and try using the plugin again.

**Comment by mkellsy** [comment]
HB 1.3 was released a few days ago, and needs a bit of testing on our end. We will update HOOBS 3 to 1.3 next week.

**Comment by colinbendell** [comment]
@mkellsy are you a maintainer on HOOBS?

**Comment by mkellsy** [comment]
@colinbendell Yep
