### ISSUE TITLE
Characteristic was supplied illegal value

### ISSUE THREAD

**Issue by rweckhoff** [colinbendell/homebridge-blink-for-home#57]
Error being thrown with homebridge-blink-for-home v3.7.1 / Homebridge 1.3.0 

[2/22/2021, 10:45:58 AM] [Blink] Battery Level for Blink Front Door is: 94
[2/22/2021, 10:51:13 AM] [Blink] Temperature for Blink Driveway is: 23.9
[2/22/2021, 10:51:13 AM] [Blink] Motion for Blink Driveway is: true
[2/22/2021, 10:51:23 AM] [Blink] **Blink Exterior Armed (Current) for Blink Exterior is: 4**
[2/22/2021, 10:51:23 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': **characteristic was supplied illegal value: number 4 exceeded maximum of 3**. See https://git.io/JtMGR for more info.
[2/22/2021, 10:51:23 AM] [Blink] Blink Exterior Armed (Target) for Blink Exterior is: 3
[2/22/2021, 10:51:33 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[2/22/2021, 10:51:43 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[

**Comment by rweckhoff** [comment]
> Error being thrown with homebridge-blink-for-home v3.7.1 / Homebridge 1.3.0
> 
> [2/22/2021, 10:45:58 AM] [Blink] Battery Level for Blink Front Door is: 94
> [2/22/2021, 10:51:13 AM] [Blink] Temperature for Blink Driveway is: 23.9
> [2/22/2021, 10:51:13 AM] [Blink] Motion for Blink Driveway is: true
> [2/22/2021, 10:51:23 AM] [Blink] **Blink Exterior Armed (Current) for Blink Exterior is: 4**
> [2/22/2021, 10:51:23 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': **characteristic was supplied illegal value: number 4 exceeded maximum of 3**. See https://git.io/JtMGR for more info.
> [2/22/2021, 10:51:23 AM] [Blink] Blink Exterior Armed (Target) for Blink Exterior is: 3
> [2/22/2021, 10:51:33 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
> [2/22/2021, 10:51:43 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
> [

Looks like there was a post-upgrade state issue.  Went into the Home app and turned off and then rearmed.  Errors disappeared.

**Comment by hunterpaul** [comment]
I’m still seeing this after rebooting everything, arming and disarming. Seems to occur any time when motion is detected

**Comment by rweckhoff** [comment]
Seeing this now instead:

[2/22/2021, 12:26:15 PM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Selected RTP Stream Configuration': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics See https://git.io/JtMGR for more info.
[2/22/2021, 12:26:15 PM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Selected RTP Stream Configuration': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics See https://git.io/JtMGR for more info.
[2/

**Comment by colinbendell** [comment]
Can you share which configuration you have set?

**Comment by rweckhoff** [comment]
> Can you share which configuration you have set?

Homebridge 1.3.1 (oznu/homebridge) 
{
    "name": "Blink",
    "username": "email@gmail.com",
    "password": “password”,
    "pin": 123456,
    "enable-liveview": false,
    "avoid-thumbnail-battery-drain": true,
    "camera-thumbnail-refresh-seconds": 3600,
    "enable-verbose-logging": false,
    "enable-debug-logging": false,
    "enable-startup-diagnostic": false,
    "platform": "Blink"
}

**Comment by murphwiz** [comment]
I’m also having the same issues

![8A776317-A4D9-4F6C-9353-CE5091B04FCC](https://user-images.githubusercontent.com/77070708/109425174-fed4ed80-79de-11eb-8fa7-52a5b6a9bf5d.jpeg)

**Comment by mtressl** [comment]
Today my logs are flooded with the **Temperature characteristic**.

[3/1/2021, 9:23:25 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.

**Comment by mtressl** [comment]
Is it possible the Blink API doesn't always return a full set of values?
Yesterday the warning vanished, and came back in the evening. Is that possible?
Currently we have low temperatures at night but quite warm during the day, so I was thinking it might be connected to the temperature ranges that can be defined within the Blink app (where for me 4°C is the minimum). So maybe that causes some failed API calls once temps drop below that?

`[3/2/2021, 9:41:10 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: **null!** Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.`

**Comment by mtressl** [comment]
One more thing I just found out:
the characteristic warning 'Current Temperature' in the HB logs goes away once you open the Blink app and open each camera's detail settings (where most likely a temperature refresh is pulled).

Will keep an eye on it if I can reproduce once the warning comes up again.

**Comment by rweckhoff** [comment]
These starting popping today for me:

[3/2/2021, 3:00:22 PM] [Blink] Privacy Mode for Blink Bedroom is: true
[3/2/2021, 3:00:22 PM] [Blink] Motion Sensor Active for Blink Front Door is: true
[3/2/2021, 3:00:22 PM] [Blink] Enabled for Blink Front Door is: true
[3/2/2021, 3:00:22 PM] [Blink] Battery State for Blink Front Door is: 2
[3/2/2021, 3:00:22 PM] [Blink] Temperature for Blink Front Door is: 25
[3/2/2021, 3:00:22 PM] [Blink] Temperature Sensor Active for Blink Front Door is: true
[3/2/2021, 3:00:22 PM] [Blink] Privacy Mode for Blink Front Door is: true
[3/2/2021, 3:00:22 PM] [Blink] Motion Sensor Active for Blink Driveway is: true
[3/2/2021, 3:00:22 PM] [Blink] Enabled for Blink Driveway is: true
[3/2/2021, 3:00:22 PM] [Blink] Battery State for Blink Driveway is: 2
[3/2/2021, 3:00:22 PM] [Blink] Temperature for Blink Driveway is: 30
[3/2/2021, 3:00:22 PM] [Blink] Temperature Sensor Active for Blink Driveway is: true
[3/2/2021, 3:00:22 PM] [Blink] Privacy Mode for Blink Driveway is: true
[3/2/2021, 3:00:22 PM] [Blink] Motion Sensor Active for Blink Gate is: true
[3/2/2021, 3:00:22 PM] [Blink] Enabled for Blink Gate is: true
[3/2/2021, 3:00:22 PM] [Blink] Battery State for Blink Gate is: 2
[3/2/2021, 3:00:22 PM] [Blink] Temperature for Blink Gate is: 26.7
[3/2/2021, 3:00:22 PM] [Blink] Temperature Sensor Active for Blink Gate is: true
[3/2/2021, 3:00:22 PM] [Blink] Privacy Mode for Blink Gate is: true
[3/2/2021, 3:00:22 PM] [Blink] Blink Exterior Armed (Current) for Blink Exterior is: 1
[3/2/2021, 3:00:22 PM] [Blink] Blink Exterior Armed (Target) for Blink Exterior is: 1
**[3/2/2021, 3:00:22 PM] [Blink] TypeError: Cannot read property 'camera_status' of undefined
    at BlinkCamera.getBattery (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:365:48)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at BatteryLevel.getCallback (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:91:13)
[3/2/2021, 3:00:22 PM] [Blink] TypeError: Cannot read property 'camera_status' of undefined
    at BlinkCamera.getBattery (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:365:48)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at BatteryLevel.getCallback (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:91:13)
[3/2/2021, 3:00:22 PM] [Blink] TypeError: Cannot read property 'camera_status' of undefined
    at BlinkCamera.getBattery (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:365:48)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at BatteryLevel.getCallback (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:91:13)
[3/2/2021, 3:00:22 PM] [Blink] TypeError: Cannot read property 'camera_status' of undefined
    at BlinkCamera.getBattery (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:365:48)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at BatteryLevel.getCallback (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:91:13)
[3/2/2021, 3:00:22 PM] [Blink] TypeError: Cannot read property 'camera_status' of undefined
    at BlinkCamera.getBattery (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:365:48)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at BatteryLevel.getCallback (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:91:13)
[3/2/2021, 3:00:22 PM] [Blink] TypeError: Cannot read property 'camera_status' of undefined
    at BlinkCamera.getBattery (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:365:48)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at BatteryLevel.getCallback (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:91:13)
[3/2/2021, 3:00:22 PM] [Blink] Battery Level for Blink Front Door is: 88
[3/2/2021, 3:00:22 PM] [Blink] Battery Level for Blink Driveway is: 82
[3/2/2021, 3:00:22 PM] [Blink] Battery Level for Blink Office is: 94
[3/2/2021, 3:00:22 PM] [Blink] Battery Level for Blink Bedroom is: 93
[3/2/2021, 3:00:22 PM] [Blink] Battery Level for Blink Living Room is: 95
[3/2/2021, 3:00:22 PM] [Blink] Battery Level for Blink Gate is: 83
[3/2/2021, 3:00:25 pm] INFO: INFO: Your plugin version is up-to-date
[3/2/2021, 3:00:25 pm] NOTICE: Sending Plugin Status to Hubitat | UpdateAvailable: false
[3/2/2021, 3:00:25 PM] [homebridge-blink-for-home] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[3/2/2021, 3:00:25 PM] [homebridge-blink-for-home] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[3/2/2021, 3:00:25 PM] [homebridge-blink-for-home] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[3/2/2021, 3:00:25 PM] [homebridge-blink-for-home] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[3/2/2021, 3:00:25 PM] [homebridge-blink-for-home] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[3/2/2021, 3:00:25 PM] [homebridge-blink-for-home] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[3/2/2021, 3:00:26 PM] [NetworkPresence] [Doodle's Phone] - connected to the network (mac: 98:09:cf:45:54:20 | ip:192.168.1.53 | hostname:?)
[3/2/2021, 3:00:31 PM] [homebridge-blink-for-home] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/2/2021, 3:00:31 PM] [homebridge-blink-for-home] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/2/2021, 3:00:31 PM] [homebridge-blink-for-home] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/2/2021, 3:00:31 PM] [homebridge-blink-for-home] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/2/2021, 3:00:31 PM] [homebridge-blink-for-home] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/2/2021, 3:00:31 PM] [homebridge-blink-for-home] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/2/2021, 3:00:42 PM] [Blink] FetchError: read ECONNRESET
    at fetch (/homebridge/node_modules/homebridge-blink-for-home/node_modules/@adobe/helix-fetch/src/fetch/index.js:97:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at cachingFetch (/homebridge/node_modules/homebridge-blink-for-home/node_modules/@adobe/helix-fetch/src/fetch/index.js:279:16)
    at BlinkAPI._request (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:128:21)
    at BlinkAPI.get (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:82:16)
    at BlinkAPI.getAccountHomescreen (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:525:16)
    at Blink.refreshData (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:721:28)
    at HomebridgeBlink.poll (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:88:13) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: 'read'
}
[3/2/2021, 3:00:43 PM] [Blink] TypeError: Cannot read property 'entries' of undefined
    at BlinkAPI._request (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:138:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at BlinkAPI.get (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:82:16)
    at BlinkAPI.getAccountHomescreen (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:525:16)
    at Blink.refreshData (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:721:28)
    at HomebridgeBlink.poll (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:88:13)
[3/2/2021, 3:01:21 PM] [NetworkPresence] [Anyone] - Someone connected to the network
[3/2/2021, 3:01:54 PM] [Blink] FetchError: read ECONNRESET
    at fetch (/homebridge/node_modules/homebridge-blink-for-home/node_modules/@adobe/helix-fetch/src/fetch/index.js:97:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at cachingFetch (/homebridge/node_modules/homebridge-blink-for-home/node_modules/@adobe/helix-fetch/src/fetch/index.js:279:16)
    at BlinkAPI._request (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:128:21)
    at BlinkAPI.get (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:82:16)
    at BlinkAPI.getAccountHomescreen (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:525:16)
    at Blink.refreshData (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:721:28)
    at HomebridgeBlink.poll (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:88:13) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: 'read'
}
[3/2/2021, 3:01:54 PM] [Blink] TypeError: Cannot read property 'entries' of undefined
    at BlinkAPI._request (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:138:55)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at BlinkAPI.get (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:82:16)
    at BlinkAPI.getAccountHomescreen (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:525:16)
    at Blink.refreshData (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:721:28)
    at HomebridgeBlink.poll (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:88:13)
[3/2/2021, 3:03:56 PM] [Blink] FetchError: read ECONNRESET
    at fetch (/homebridge/node_modules/homebridge-blink-for-home/node_modules/@adobe/helix-fetch/src/fetch/index.js:97:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at cachingFetch (/homebridge/node_modules/homebridge-blink-for-home/node_modules/@adobe/helix-fetch/src/fetch/index.js:279:16)
    at BlinkAPI._request (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:128:21)
    at BlinkAPI.get (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:82:16)
    at BlinkAPI.getAccountHomescreen (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:525:16)
    at Blink.refreshData (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:721:28)
    at HomebridgeBlink.poll (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:88:13) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: 'read'
}
[3/2/2021, 3:03:56 PM] [Blink] TypeError: Cannot read property 'entries' of undefined
    at BlinkAPI._request (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:138:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at BlinkAPI.get (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:82:16)
    at BlinkAPI.getAccountHomescreen (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:525:16)
    at Blink.refreshData (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:721:28)
    at HomebridgeBlink.poll (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:88:13)**

**Comment by mtressl** [comment]
The warning 'Current Temperature' appeared again tonight. Not 100% sure, but seems once temperature falls below a certain value it gets missing. Once it's missing from the API (?) the Blink for Home plugin writes `Null`, though sending it to HomeKit and causing the warning.

Maybe just keep the old value if there is no correct answer from the Blink API?

**Comment by WhooKnew** [comment]
[05/03/2021, 06:40:19] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:40:19] [Blink] Blink Home Armed (Target) for Blink Home is: 3
[05/03/2021, 06:40:19] [Blink] Blink Home Armed (Current) for Blink Home is: 4
[05/03/2021, 06:40:29] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:40:39] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:40:49] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:40:59] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:41:09] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:41:19] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:41:29] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:41:39] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:41:50] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:42:00] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:42:10] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:42:20] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:42:30] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:42:40] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:42:50] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:43:00] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:43:10] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:43:20] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:43:31] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[05/03/2021, 06:43:41] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.

I get this failure...

**Comment by colinbendell** [comment]
I've added a new check to ensure that this value is in range. I'll add it to the next release

**Comment by colinbendell** [comment]
There was an unfortunate network recovery bug that caused another failure when trying to recover from a network connection failure. It was fixed in 3.7.2

**Comment by rweckhoff** [comment]
Both items remain after 3.7.2 for me

[3/8/2021, 8:51:29 AM] [Blink] Temperature for Blink Gate is: 22.8
[3/8/2021, 9:06:23 AM] [Blink] Temperature for Blink Driveway is: 20.6
[3/8/2021, 9:27:52 AM] [Blink] FetchError: read ECONNRESET
    at fetch (/homebridge/node_modules/homebridge-blink-for-home/node_modules/@adobe/helix-fetch/src/fetch/index.js:97:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at cachingFetch (/homebridge/node_modules/homebridge-blink-for-home/node_modules/@adobe/helix-fetch/src/fetch/index.js:279:16)
    at BlinkAPI._request (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:128:21)
    at BlinkAPI.get (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:82:16)
    at BlinkAPI.getAccountHomescreen (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:526:16)
    at Blink.refreshData (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:730:28)
    at HomebridgeBlink.poll (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:88:13) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: 'read'
}
[3/8/2021, 9:40:05 am] GOOD: Refreshing All Device Data
[3/8/2021, 9:40:06 am] NOTICE: Temperature Unit is Now: (F)
[3/8/2021, 9:40:06 am] NOTICE: Updating Global Values | HubIP: 192.168.1.220 | UsingCloud: false
[3/8/2021, 9:40:06 am] WARN: Devices to Remove: (0) []
[3/8/2021, 9:40:06 am] INFO: Devices to Update: (28)
[3/8/2021, 9:40:06 am] GOOD: Devices to Create: (0) []
[3/8/2021, 9:40:06 am] ALERT: Total Initialization Time: (1 seconds)
[3/8/2021, 9:40:06 am] NOTICE: Unknown Capabilities: []
[3/8/2021, 9:40:06 am] INFO: Hubitat DeviceCache Size: (28)
[3/8/2021, 9:40:06 am] INFO: Checking Package Version for Updates...
[3/8/2021, 9:40:10 am] INFO: INFO: Your plugin version is up-to-date
[3/8/2021, 9:40:10 am] NOTICE: Sending Plugin Status to Hubitat | UpdateAvailable: false
heatingSetpoint:  70
coolingSetpoint:  75
[3/8/2021, 9:51:23 AM] [Blink] Temperature for Blink Gate is: 36.1
[3/8/2021, 10:06:27 AM] [Blink] Temperature for Blink Front Door is: 22.8
[3/8/2021, 10:06:27 AM] [Blink] Temperature for Blink Driveway is: 25
[3/8/2021, 10:06:27 AM] [Blink] Temperature for Blink Gate is: 35.6
[3/8/2021, 10:06:37 AM] [Blink] Blink Exterior Armed (Current) for Blink Exterior is: 4
[3/8/2021, 10:06:37 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[3/8/2021, 10:06:37 AM] [Blink] Blink Exterior Armed (Target) for Blink Exterior is: 3
[3/8/2021, 10:06:37 AM] [Blink] Motion for Blink Gate is: true
[3/8/2021, 10:06:47 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[3/8/2021, 10:06:57 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[3/8/2021, 10:07:08 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[3/8/2021, 10:07:18 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[3/8/2021, 10:07:28 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[3/8/2021, 10:07:38 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[3/8/2021, 10:07:48 AM] [homebridge-blink-for-home] This plugin generated a warning from the characteristic 'Security System Target State': characteristic was supplied illegal value: number 4 exceeded maximum of 3. See https://git.io/JtMGR for more info.
[3/8/2021, 10:07:58 AM] [Blink] Motion for Blink Gate is: false

**Comment by colinbendell** [comment]
Ah. I see the problem now. This is the result of motion detection which isn't valid in the TargetState characteristic. Should be a simple fix.

**Comment by jeremybdk** [comment]
For me, any motion when armed will trigger an event on the Homekit Alarm system instead of the motion detector.
Each team a motion is detected I receive a notification saying that the system was armed for away.

**Comment by WhooKnew** [comment]
@jeremybdk - i got the same problem

**Comment by mtressl** [comment]
> Ah. I see the problem now. This is the result of motion detection which isn't valid in the TargetState characteristic. Should be a simple fix.

Hi @colinbendell 
will you fix these Characteristic errors regarding Temperature and so on in the plugin? We had a cold night and day today and my logs are full of those messages.
Thanks in advance!

**Comment by gdotp01** [comment]
I’m seeing the same problem and it seems to start when the outside temperature drops below a certain value, 
![C1AE59E8-178B-4929-8543-9A5DB765A476](https://user-images.githubusercontent.com/50060482/114514955-c22e2000-9c33-11eb-9a0f-47ebcafaafc5.png)

**Comment by jeremybdk** [comment]
For me it's every time a motion is triggered, it seems that there is a few characteristic with illegal values.
