### ISSUE TITLE
Triggering Blink 3rd party notification and breaking all functionality.

### ISSUE THREAD

**Issue by xImportExportx** [colinbendell/homebridge-blink-for-home#65]
After 1-2 days I get the following errors in Homebridge logs. The first one repeats for a few hours until the child bridge process restarts.

[4/9/2021, 2:20:11 AM] [Blink] FetchError: The pending stream has been canceled (caused by: read ECONNRESET)
    at fetch (/homebridge/node_modules/homebridge-blink-for-home/node_modules/@adobe/helix-fetch/src/fetch/index.js:97:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at cachingFetch (/homebridge/node_modules/homebridge-blink-for-home/node_modules/@adobe/helix-fetch/src/fetch/index.js:279:16)
    at BlinkAPI._request (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:128:21)
    at BlinkAPI.login (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:309:21)
    at BlinkAPI._request (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:135:13)
    at BlinkAPI.get (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:82:16)
    at BlinkAPI.getAccountHomescreen (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:526:16)
    at Blink.refreshData (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:730:28) {
  type: 'system',
  errno: 'ERR_HTTP2_STREAM_CANCEL',
  code: 'ERR_HTTP2_STREAM_CANCEL',
  erroredSysCall: undefined
}
Error [ERR_HTTP2_STREAM_CANCEL]: The pending stream has been canceled (caused by: read ECONNRESET)
    at closeSession (internal/http2/core.js:1063:20)
    at ClientHttp2Session.destroy (internal/http2/core.js:1420:5)
    at TLSSocket.socketOnError (internal/http2/core.js:2833:13)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[4/9/2021, 2:20:11 AM] [Blink] Child bridge process ended
[4/9/2021, 2:20:11 AM] [Blink] Process Ended. Code: 1, Signal: null
[4/9/2021, 2:20:18 AM] [Blink] Restarting Process...
Initializing HAP-NodeJS v0.9.4...
[4/9/2021, 2:20:19 AM] [Blink] Launched child bridge with PID 2066730
[4/9/2021, 2:20:19 AM] Registering platform 'homebridge-blink-for-home.Blink'
[4/9/2021, 2:20:19 AM] [Blink] Loaded homebridge-blink-for-home v3.7.2 child bridge successfully
[4/9/2021, 2:20:19 AM] Loaded 4 cached accessories from cachedAccessories.0E514CB8A396.
Preparing Advertiser for 'Blink C23D' using ciao backend!
[4/9/2021, 2:20:19 AM] [Blink] Init Blink
Starting to advertise 'Blink C23D' using ciao backend!
[4/9/2021, 2:20:19 AM] Homebridge v1.3.4 (Blink) is running on port 48074.
[4/9/2021, 2:20:20 AM] [Blink] TypeError: Cannot read property 'token' of undefined
    at BlinkAPI.login (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:316:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HomebridgeBlink.setupBlink (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:110:13)
    at HomebridgeBlink.init (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:48:26)
[4/9/2021, 2:20:20 AM] [Blink] Error: Unable to authenticate with Blink. Missing 2FA PIN?
    at HomebridgeBlink.setupBlink (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:117:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HomebridgeBlink.init (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:48:26)
[4/9/2021, 2:20:20 AM] [Blink] NOTE: Blink devices in HomeKit will not be responsive.

When I then try and login in the blink app I get the following error
![IMG_FD4C34E30349-1](https://user-images.githubusercontent.com/30048021/114240636-ac231580-993c-11eb-9430-782fbe5545e1.jpeg)

I have to remove user/pass from blink for home plugin, wait 30-60 mins then reauthenticate to clear. After a couple of days it reoccurs.

Along with this I receive a 2fa text every 1 hour and 1 min exactly now. Can't remember when this started but its REALLY annoying.

**Comment by colinbendell** [comment]
did you fix your issue?

**Comment by xImportExportx** [comment]
Yes it ended up being a combination of third party things and my mistake on one of them.
