### ISSUE TITLE
No SMS received

### ISSUE THREAD

**Issue by ayman** [colinbendell/homebridge-blink-for-home#76]
Maybe related to #64 but I never get a SMS 2FA ping. 

```
        {
            "name": "Blink",
            "username": "me@example.com",
            "password": "super-password",
            "pin": "",
            "avoid-thumbnail-battery-drain": true,
            "enable-verbose-logging": false,
            "enable-debug-logging": false,
            "enable-startup-diagnostic": false,
            "platform": "Blink"
        }
```

I've tried `"pin": "",`, `"pin": null`, and just removing the `pin` key too in the config.  Just logs back a 401 each time I restart homebridge and no SMS pin.

```
[8/8/2021, 4:47:54 PM] [Blink] Error: 401 Unauthorized
    at BlinkAPI._request (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:167:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at BlinkAPI._request (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:160:24)
    at BlinkAPI.get (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:82:16)
    at BlinkAPI.getAccountHomescreen (/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:526:16)
    at Blink.refreshData (/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:730:28)
    at HomebridgeBlink.setupBlink (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:111:13)
    at HomebridgeBlink.init (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:48:26)
[8/8/2021, 4:47:54 PM] [Blink] Error: Unable to authenticate with Blink. Missing 2FA PIN?
    at HomebridgeBlink.setupBlink (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:117:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HomebridgeBlink.init (/homebridge/node_modules/homebridge-blink-for-home/src/index.js:48:26)
[8/8/2021, 4:47:54 PM] [Blink] NOTE: Blink devices in HomeKit will not be responsive.
```

Any thoughts here?  Not sure where to go.

**Comment by ayman** [comment]
Oddly and like #64 it started working after disabling the plugin for a day and then trying again.  Perhaps a new blink account needed time before the other auth requests would process?
