### ISSUE TITLE
[Blink] SyntaxError: Unexpected end of JSON input at JSON.parse

### ISSUE THREAD

**Issue by jamesgrant1981** [colinbendell/homebridge-blink-for-home#78]
Hello :) 
I hope someone can shed some light on this error I'm receiving...
So have installed the plugin, and the first time loading it sent me my verification code, which I've added, however I've never been able to actually start this plugin. This is the error:

Ive searched the issues here to see if anyone else is having this, but can't find anything similar. :( 

It does say unable to authenticate, however it requested my 2FA code which I added to the preferences.
There's errors before this... so unsure if it's this error that's making it unhappy. 

- Homebridge: 1.3.4
- Node.js: 14.0.0
- NPM: 6.14.4
- OS: macOS High Sierra

```

[17/08/2021, 11:40:03] [Blink] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Response.json (/usr/local/lib/node_modules/homebridge-blink-for-home/node_modules/@adobe/helix-fetch/src/fetch/body.js:161:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at BlinkAPI._request (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:143:26)
    at BlinkAPI.login (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:309:21)
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/index.js:110:13)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/index.js:48:26)
[17/08/2021, 11:40:03] [Blink] Error: Unable to authenticate with Blink. Missing 2FA PIN?
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/index.js:117:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/index.js:48:26)
[17/08/2021, 11:40:03] [Blink] NOTE: Blink devices in HomeKit will not be responsive.

```

**Comment by atastrophic** [comment]
having same issue here any updates for you?

**Comment by crlppr** [comment]
Same issue for me. Thanks.
HomeBridge: 1.6.1

[20/05/2023, 17:17:08] [Camara Pasillo] getBlinkStatus()
[20/05/2023, 17:17:09] [Camara Pasillo] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at CacheableResponse.json (/var/lib/homebridge/node_modules/homebridge-blink-for-home/node_modules/@adobe/fetch/src/fetch/cacheableResponse.js:93:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlinkAPI._request (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:290:26)
    at BlinkAPI.get (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:229:16)
    at BlinkAPI.getBlinkStatus (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/blink-api.js:1282:16)
    at anonymize (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:469:25)
    at BlinkHAP.diagnosticDebug (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:499:13)
    at HomebridgeBlink.setupBlink (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[20/05/2023, 17:17:09] [Camara Pasillo] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at anonymize (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:472:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BlinkHAP.diagnosticDebug (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/blink.js:499:13)
    at HomebridgeBlink.setupBlink (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[20/05/2023, 17:17:09] [Camara Pasillo] Error: Blink Authentication failed.
    at HomebridgeBlink.setupBlink (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:116:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HomebridgeBlink.init (/var/lib/homebridge/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[20/05/2023, 17:17:09] [Camara Pasillo] NOTE: Blink devices in HomeKit will not be responsive.

**Comment by eklass** [comment]
@crlppr downgrad HAM to ~~3.5.0~~ **5.3.0** and the error should be gone and the datapoints will appear :)

**Comment by sagar5534** [comment]
@eklass how do you downgrade HAM to 3.5.0?

**Comment by crlppr** [comment]
> @crlppr downgrad HAM to 3.5.0 and the error should be gone and the datapoints will appear :)

Thanks a lot eklass, but i have been trying to do that, even trying to understand what is HAM, and i don't know how to do it. Sorry for this question, but could you give me some clue about how to do that. 
Thanks in advance

**Comment by eklass** [comment]
> @eklass how do you downgrade HAM to 3.5.0?


Hi, sorry for forgetting to answer.

You can downgrade HAM by enabling the expert mode in iobroker and then just choose the version as shown below:
![image](https://github.com/colinbendell/homebridge-blink-for-home/assets/8988552/2556f1a6-0882-4708-921f-02d429cdf5ce)
![image](https://github.com/colinbendell/homebridge-blink-for-home/assets/8988552/d1506a46-1edc-4d88-8afb-917a3c2997b8)



> > @crlppr downgrad HAM to 3.5.0 and the error should be gone and the datapoints will appear :)
> 
> Thanks a lot eklass, but i have been trying to do that, even trying to understand what is HAM, and i don't know how to do it. Sorry for this question, but could you give me some clue about how to do that. Thanks in advance
What is HAM?

HAM stands for **H**omebridge **a**ccessories **m**anager)
https://github.com/ioBroker/ioBroker.ham

With this manager, you can install plugins like blink-for-home even if you do not have a homebridge, or even do not want to use one. ([Wrapper Mode](https://github.com/ioBroker/ioBroker.ham#default-wrapper-mode))

Off Topic (not thread related): Homebridge is normaly used for connecting devices f.e. into your smart home. Homebridge can be linked to your Apple Home App and then you can access your devices over the bridge.

Best regards

**Comment by crlppr** [comment]
Thanks a lot. I did it and now that error has disappeared. The plugin is now starting without errors. Now I have another issue but this is related to the issue #110. I think we can close this. Thanks a lot once again. 

Just a very small topic. in this thread is described as "downgrade HAM to 3.5.0", but I think you really want to say. "5.3.0" as described in your picture.

**Comment by eklass** [comment]
Nice that it worked out for you.
Thanks for the hint with the typo in the version number. I meant in deed 5.3.0.
Have a nice week!
