### ISSUE TITLE
Blink Mini thumbnails no longer working

### ISSUE THREAD

**Issue by ecws2021** [colinbendell/homebridge-blink-for-home#99]
Yesterday I noticed my Blink Mini thumbnails were no longer showing up. 
I rebooted homebridge and my raspberry pi multiple times. 
I rebooted all of the cameras multiple times, did not work. 
I disabled and re-enabled the plugin and it did not work. 
I uninstalled and re-installed the plugin and it did not work. 
I tried running it as a child bridge, did not work. 

I can still arm/disarm. 
When cameras are armed, they will show a thumbnail of the last motion event (whether that was minutes or days ago)
When cameras are disarmed, they show the grey "privacy mode, blink cameras disarmed" screen. 
I can hear the cameras taking the thumbnail, but they are not showing up in homebridge. 

I'm at a total loss as to what has happened. No settings were changed in homebridge, homekit or my raspberry pi. 
So perhaps Blink has changed something on their end?

Please help!!!!!

**Comment by colinbendell** [comment]
Can you clarify what behaviour you expect it to be doing? Do you expect the privacy mode to display? Do you want it to be taking still images even when it is not armed? 

I think there was a bug when the thumbnails would be taken, but not shown when the 'privacy mode' switch was enabled. Change that switch setting to off and you should now see it.

**Comment by ecws2021** [comment]
Previously it was taking a still image whenever I checked my "home" app, regardless if it was armed or not. 

I do have privacy mode switched off and still am not getting fresh thumbnails. I see outdated stills of the last time it detected motion.

**Comment by xImportExportx** [comment]
@colinbendell im suffering the same issue with Blink new external cameras too. HomeKit updates stills to last motion not as previously with a fresh snapshot. Can’t pin down when it started but at least a couple weeks

**Comment by colinbendell** [comment]
The root issue was that blink changed the format of their thumbnails, so the plugin wasn't able to accurately detect if the thumbnail had changed. Give the 3.9 version a try and see if it has remedied the problem for you.

**Comment by xImportExportx** [comment]
@colinbendell From what I can see now the behaviour is different (and was in the release notes). Now my thumbnails only update if the cameras are armed. Previously they just updated all the time which was exactly how I liked it. Any chance we can return to that behaviour or have it as an option? I disarm my cameras in the day but like to check in using home and thumbnails.

**Comment by bluntiless** [comment]
Hello, thumbnails are not working and I now get this in Terminal, can you advise what is wrong? It loaded correctly the firs time:
[01/04/2022, 13:14:33] [Blink] getSirens()
[01/04/2022, 13:14:34] [Blink] GET /sirens (404 Not Found)
[01/04/2022, 13:14:34] [Blink] GET /sirens
[01/04/2022, 13:14:34] [Blink] Error: GET /sirens (404 Not Found)
    at BlinkAPI._request (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:342:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BlinkAPI.get (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:228:16)
    at BlinkAPI.getSirens (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink-api.js:1114:16)
    at anonymize (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:469:25)
    at BlinkHAP.diagnosticDebug (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:507:13)
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[01/04/2022, 13:14:34] [Blink] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at anonymize (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:472:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BlinkHAP.diagnosticDebug (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:507:13)
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:112:59)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[01/04/2022, 13:14:34] [Blink] Error: Blink Authentication failed.
    at HomebridgeBlink.setupBlink (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:116:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/homebridge/index.js:41:26)
[01/04/2022, 13:14:34] [Blink] NOTE: Blink devices in HomeKit will not be responsive.

**Comment by colinbendell** [comment]
I believe that error is from the diagnostic debug. can you disable that?

**Comment by bluntiless** [comment]
Hi thanks that worked. The thumbnail is not updating and liveview says no response. I have XT model from 2019. Does this work usually?

**Comment by colinbendell** [comment]
Homekit sometimes gets in a weird state. try disabling motion and then arm + enable motion. (This functionally turns 'manual-status' in HAP to 'offline' and then back to 'online') This should get Homekit out of the funk and get it polling for new imagse.

**Comment by bluntiless** [comment]
Hi @colinbendell, rolled back to the previous version and Liveview is working. However they don't show up in Home Apps on MacBook, iPad or ATV4?

**Comment by Hobkalabat** [comment]
Guten Tag! Seit fast 7 Tagen habe ich das Problem, dass ich KEINE Ansicht mehr in HomeKit habe!
Die Ansicht der Kameras zeigt eine KEINE Antwort ....
Es lässt sich nichts beheben.
BITTE FEEDBACK mit Lösung

Danke
